[package]
name = "scaffold"
version = "0.1.0"
authors = ["gmvbr"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3"
serde = "1.0.117"
serde_derive = "1.0.117"

[profile.test]
opt-level = 1
codegen-units = 1